# Generated by Django 5.1 on 2024-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peluche',
            fields=[
                ('idpeluche', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('idproveedor', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('tamaño', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('tipotela', models.CharField(max_length=20)),
                ('idsucursal', models.CharField(max_length=6)),
            ],
        ),
    ]
