# Generated by Django 5.1.2 on 2024-11-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='idempleado',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
