# Generated by Django 5.1.2 on 2024-11-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idsucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('idempleado', models.CharField(max_length=6)),
                ('horario', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
    ]
